---
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t "$REPOSITORY_URI:$IMAGE_TAG-$CODEBUILD_START_TIME" .
      - docker tag "$REPOSITORY_URI:$IMAGE_TAG-$CODEBUILD_START_TIME" "$REPOSITORY_URI:$IMAGE_TAG-$CODEBUILD_START_TIME"

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push "$REPOSITORY_URI:$IMAGE_TAG-$CODEBUILD_START_TIME"

      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' "$REPOSITORY_URI:$IMAGE_TAG-$CODEBUILD_START_TIME"  > imageDetail.json
      - cat imageDetail.json

      - sed -i 's|<APP_NAME>|'$APP_NAME'|g' appspec.yaml taskdef.json
      - sed -i 's|<SERVICE_PORT>|'$SERVICE_PORT'|g' appspec.yaml taskdef.json
      - sed -i 's|<IAM_EXEC_ROLE>|'$IAM_EXEC_ROLE'|g' taskdef.json
      - sed -i 's|<IMAGE_NAME>|'$REPOSITORY_URI'\:'$IMAGE_TAG-$CODEBUILD_START_TIME'|g' taskdef.json
      - sed -i 's|<CPU>|'$CPU'|g' taskdef.json
      - sed -i 's|<MEMORY>|'$MEMORY'|g' taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json
