---
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--compact
        - --args=--download-external-modules=True
